# -*- coding: utf-8 -*-
"""K Means Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NmTtHiutb3Uoeki-nfXPBZyJ6JMuZRnN

# K Means Clustering

## Importing libraries
"""

import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt

"""## Importing dataset"""

dataset = pd.read_csv('/content/Amazon.com Clusturing Model.csv')
X = dataset.iloc[:, 3:5].values

"""## Optimal number of clusters via Elbow Method"""

from sklearn.cluster import KMeans
wcss = []

for i in range(1, 11):
  kmeans = KMeans(n_clusters = i, random_state = 42, init = 'k-means++')
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11), wcss)
plt.title('clusters via Elbow Method')
plt.xlabel('cluster')
plt.ylabel('wcss')

"""## K Means Model Training on Training set"""

kmeans = KMeans(n_clusters = 4, random_state = 42, init = 'k-means++')
y_means = kmeans.fit_predict(X)

print(y_means)

"""## Visualizing Clusters"""

plt.scatter(X[y_means==0, 0], X[y_means==0, 1], s = 100, c = 'magenta' , label = 'cluster 1')
plt.scatter(X[y_means==1, 0], X[y_means==1, 1], s = 100, c = 'red' , label = 'cluster 2')
plt.scatter(X[y_means==2, 0], X[y_means==2, 1], s = 100, c = 'blue' , label = 'cluster 3')
plt.scatter(X[y_means==3, 0], X[y_means==3, 1], s = 100, c = 'cyan' , label = 'cluster 4')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300, c = 'black', label = 'Centroids')
plt.title('clustersof amazon')
plt.xlabel('annual income')
plt.ylabel('purchase rating')
plt.legend()
plt.show()